(() => {
  "use strict";
  const DATA=window.TBJ_DATA;if(!DATA)return;
  const slug=document.body.dataset.collection,collection=DATA.collections.find(item=>item.slug===slug);
  if(!collection){document.body.innerHTML='<p class="noscript">Collection not found. <a href="../index.html">Return to THE B JAPAN</a>.</p>';return}
  const copy={
    en:{mainArchive:"MAIN ARCHIVE ↗",backToArchive:"THE B JAPAN",galleries:"GALLERIES",media:"MEDIA",updated:"UPDATED",searchGalleries:"SEARCH GALLERIES...",sort:"SORT",sourceOrder:"SOURCE ORDER",newest:"NEWEST",largest:"MOST MEDIA",openSource:"OPEN SOURCE FOLDER",noResults:"NO GALLERIES FOUND",backTop:"BACK TO TOP ↑",openFolder:"OPEN FOLDER",downloadNote:"OPEN OR DOWNLOAD EACH FILE USING THE LINKS BELOW.",openGallery:"OPEN GALLERY",sections:"SECTIONS",results:"GALLERIES",view:"VIEW",download:"DOWNLOAD",play:"PLAY",images:"PHOTOS",videos:"VIDEOS",documents:"DOCUMENTS"},
    ko:{mainArchive:"메인 아카이브 ↗",backToArchive:"더비 재팬",galleries:"갤러리",media:"미디어",updated:"업데이트",searchGalleries:"갤러리 검색...",sort:"정렬",sourceOrder:"원본 순서",newest:"최신순",largest:"미디어 많은 순",openSource:"원본 폴더 열기",noResults:"갤러리를 찾을 수 없습니다",backTop:"맨 위로 ↑",openFolder:"폴더 열기",downloadNote:"아래 링크를 사용해 각 파일을 열거나 다운로드할 수 있습니다.",openGallery:"갤러리 열기",sections:"섹션",results:"갤러리",view:"보기",download:"다운로드",play:"재생",images:"사진",videos:"영상",documents:"문서"}
  };
  const state={lang:localStorage.getItem("tbzJapanLang")==="ko"?"ko":"en",query:"",sort:"source",current:null};
  const $=selector=>document.querySelector(selector),driveFolder=id=>`https://drive.google.com/drive/folders/${encodeURIComponent(id)}`,thumb=(id,width=1000)=>`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w${width}`,view=id=>`https://drive.google.com/file/d/${encodeURIComponent(id)}/view`,download=id=>`https://drive.google.com/uc?export=download&id=${encodeURIComponent(id)}`,preview=id=>`https://drive.google.com/file/d/${encodeURIComponent(id)}/preview`;
  const number=value=>new Intl.NumberFormat(state.lang==="ko"?"ko-KR":"en-US").format(value||0);
  const date=value=>{if(!value)return"—";const current=new Date(value);return state.lang==="ko"?new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit"}).format(current):new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(current).toUpperCase()};
  function sortedGalleries(){const items=collection.galleries.map((gallery,index)=>({gallery,index})).filter(({gallery})=>gallery.name.toLocaleLowerCase().includes(state.query));if(state.sort==="newest")items.sort((a,b)=>(b.gallery.updatedAt||"").localeCompare(a.gallery.updatedAt||""));if(state.sort==="largest")items.sort((a,b)=>b.gallery.itemCount-a.gallery.itemCount);if(state.sort==="az")items.sort((a,b)=>a.gallery.name.localeCompare(b.gallery.name,undefined,{numeric:true}));return items}
  function galleryCard(gallery,index){
    const article=document.createElement("article");article.className="card";const imageButton=document.createElement("button");imageButton.className="thumb";imageButton.type="button";imageButton.dataset.open=gallery.id;imageButton.setAttribute("aria-label",`${copy[state.lang].openGallery}: ${gallery.name}`);
    if(gallery.coverId){const image=document.createElement("img");image.src=thumb(gallery.coverId);image.alt="";image.loading="lazy";image.referrerPolicy="no-referrer";imageButton.append(image)}else{const placeholder=document.createElement("span");placeholder.className="thumb-placeholder";placeholder.textContent=gallery.documentCount?"DOCUMENT":"FOLDER";imageButton.append(placeholder)}
    const badge=document.createElement("span");badge.className="number";badge.textContent=String(index+1).padStart(2,"0");const count=document.createElement("span");count.className="photo-count";count.textContent=`${number(gallery.itemCount)} ${copy[state.lang].media}`;imageButton.append(badge,count);
    const info=document.createElement("div");info.className="card-info";const eyebrow=document.createElement("span");eyebrow.className="eyebrow";eyebrow.textContent=`${collection.nameEn} / ${String(index+1).padStart(2,"0")}`;const title=document.createElement("h2");title.textContent=gallery.name;
    const meta=document.createElement("div");meta.className="meta";[[copy[state.lang].images,number(gallery.imageCount)],[copy[state.lang].videos,number(gallery.videoCount)],[copy[state.lang].documents,number(gallery.documentCount)],[copy[state.lang].updated,date(gallery.updatedAt)]].forEach(([label,value])=>{const labelElement=document.createElement("span");labelElement.textContent=label;const valueElement=document.createElement("strong");valueElement.textContent=value;meta.append(labelElement,valueElement)});
    const actions=document.createElement("div");actions.className="card-actions";const openButton=document.createElement("button");openButton.type="button";openButton.dataset.open=gallery.id;openButton.textContent=`${copy[state.lang].openGallery} →`;const source=document.createElement("a");source.href=driveFolder(gallery.folderId);source.target="_blank";source.rel="noopener noreferrer";source.textContent=`${copy[state.lang].openFolder} ↗`;actions.append(openButton,source);info.append(eyebrow,title,meta,actions);article.append(imageButton,info);return article;
  }
  function renderCards(){const items=sortedGalleries(),cards=$("#cards");cards.replaceChildren();items.forEach(({gallery},index)=>cards.append(galleryCard(gallery,index)));$("#resultsCount").textContent=`${number(items.length)} ${copy[state.lang].results}`;$("#empty").hidden=items.length!==0}
  function mediaCard(item){
    const figure=document.createElement("figure");figure.className=`photo media-${item.type}`;
    if(item.type==="image"){const image=document.createElement("img");image.src=thumb(item.id,1600);image.alt=item.name;image.loading="lazy";image.referrerPolicy="no-referrer";if(item.width&&item.height){image.width=item.width;image.height=item.height}figure.append(image)}
    else if(item.type==="video"){const playButton=document.createElement("button");playButton.className="media-preview";playButton.type="button";playButton.dataset.play=item.id;playButton.setAttribute("aria-label",`${copy[state.lang].play}: ${item.name}`);const image=document.createElement("img");image.src=thumb(item.id,1200);image.alt="";image.loading="lazy";image.referrerPolicy="no-referrer";const badge=document.createElement("span");badge.className="play-badge";badge.textContent=`▶ ${copy[state.lang].play}`;playButton.append(image,badge);figure.append(playButton)}
    else{const documentCover=document.createElement("a");documentCover.className="document-cover";documentCover.href=view(item.id);documentCover.target="_blank";documentCover.rel="noopener noreferrer";const type=document.createElement("strong");type.textContent=item.type==="audio"?"AUDIO":"DOCUMENT";const hint=document.createElement("span");hint.textContent=`${copy[state.lang].view} ↗`;documentCover.append(type,hint);figure.append(documentCover)}
    const bar=document.createElement("figcaption");bar.className="photo-bar";const name=document.createElement("span");name.className="photo-name";name.title=item.name;name.textContent=item.name;const links=document.createElement("span");links.className="photo-links";if(item.type==="video"){const playLink=document.createElement("button");playLink.type="button";playLink.dataset.play=item.id;playLink.textContent=`${copy[state.lang].play} ▶`;links.append(playLink)}const viewLink=document.createElement("a");viewLink.href=view(item.id);viewLink.target="_blank";viewLink.rel="noopener noreferrer";viewLink.textContent=`${copy[state.lang].view} ↗`;const downloadLink=document.createElement("a");downloadLink.href=download(item.id);downloadLink.target="_blank";downloadLink.rel="noopener noreferrer";downloadLink.textContent=`${copy[state.lang].download} ↓`;links.append(viewLink,downloadLink);bar.append(name,links);figure.append(bar);return figure;
  }
  function renderOpenGallery(){const gallery=state.current;if(!gallery)return;$("#dialogTitle").textContent=gallery.name;$("#dialogKicker").textContent=`${collection.nameEn} · ${number(gallery.itemCount)} ${copy[state.lang].media}`;$("#dialogDrive").href=driveFolder(gallery.folderId);const groups=$("#galleryGroups");groups.replaceChildren();gallery.groups.forEach(group=>{const section=document.createElement("section");section.className="scan-group";const heading=document.createElement("h3");heading.className="group-heading";heading.textContent=`${group.name} / ${number(group.media.length)} ${copy[state.lang].media}`;const grid=document.createElement("div");grid.className="photo-grid";group.media.forEach(item=>grid.append(mediaCard(item)));section.append(heading,grid);groups.append(section)})}
  function openGallery(id){state.current=collection.galleries.find(gallery=>gallery.id===id);if(!state.current)return;renderOpenGallery();$("#galleryDialog").showModal();document.body.classList.add("modal-open")}
  function openPlayer(id){$("#videoPlayer").src=preview(id);$("#playerOverlay").hidden=false}
  function closePlayer(){$("#playerOverlay").hidden=true;$("#videoPlayer").removeAttribute("src")}
  function applyLanguage(){const lang=copy[state.lang];document.documentElement.lang=state.lang==="ko"?"ko":"en";$("#langToggle").textContent=state.lang==="ko"?"KOR":"EN";document.querySelectorAll("[data-i18n]").forEach(element=>{element.textContent=lang[element.dataset.i18n]});document.querySelectorAll("[data-i18n-placeholder]").forEach(element=>{element.placeholder=lang[element.dataset.i18nPlaceholder]});const title=$("#collectionTitle");title.replaceChildren();const solid=document.createElement("span");solid.className="solid";solid.textContent=state.lang==="ko"&&collection.nameKo?collection.nameKo:collection.nameEn;const outline=document.createElement("span");outline.className="outline";outline.textContent="THE B JAPAN";title.append(solid,outline);const length=solid.textContent.length;$(".collection-masthead").classList.toggle("title-long",length>17);$(".collection-masthead").classList.toggle("title-very-long",length>23);$("#galleryCount").textContent=number(collection.galleryCount);$("#mediaCount").textContent=number(collection.itemCount);$("#updatedDate").textContent=date(collection.updatedAt);renderCards();if(state.current&&$("#galleryDialog").open)renderOpenGallery()}
  document.title=`${collection.nameEn} — THE B JAPAN`;$("#collectionDrive").href=driveFolder(collection.id);$("#search").addEventListener("input",event=>{state.query=event.target.value.trim().toLocaleLowerCase();renderCards()});$("#sortFilter").addEventListener("change",event=>{state.sort=event.target.value;renderCards()});$("#cards").addEventListener("click",event=>{const target=event.target.closest("[data-open]");if(target)openGallery(target.dataset.open)});$("#galleryGroups").addEventListener("click",event=>{const target=event.target.closest("[data-play]");if(target)openPlayer(target.dataset.play)});$("#closePlayer").addEventListener("click",closePlayer);$("#playerOverlay").addEventListener("click",event=>{if(event.target===$("#playerOverlay"))closePlayer()});$("#closeDialog").addEventListener("click",()=>$("#galleryDialog").close());$("#galleryDialog").addEventListener("close",()=>{closePlayer();document.body.classList.remove("modal-open");state.current=null;$("#galleryGroups").replaceChildren()});$("#galleryDialog").addEventListener("click",event=>{if(event.target===$("#galleryDialog"))$("#galleryDialog").close()});$("#langToggle").addEventListener("click",()=>{state.lang=state.lang==="en"?"ko":"en";localStorage.setItem("tbzJapanLang",state.lang);applyLanguage()});applyLanguage();
})();
